global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8081']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'tenant-service'
    static_configs:
      - targets: ['tenant-service:8082']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'crm-service'
    static_configs:
      - targets: ['crm-service:8083']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'lms-service'
    static_configs:
      - targets: ['lms-service:8084']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'pos-service'
    static_configs:
      - targets: ['pos-service:8085']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'checkin-service'
    static_configs:
      - targets: ['checkin-service:8086']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:8087']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'file-service'
    static_configs:
      - targets: ['file-service:8088']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'hrm-service'
    static_configs:
      - targets: ['hrm-service:8089']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
